# SPDX-FileCopyrightText: © 2024 Tim Weber
#
# SPDX-License-Identifier: CC-BY-4.0

name: REUSE Compliance Check

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  reuse-compliance-check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: REUSE Compliance Check
      uses: fsfe/reuse-action@v5
